#if UNITY_EDITOR
using System.Collections.Generic;
using System.IO;
using System.Text;
using UniMasterLinker.Util;
using UnityEditor;
using UnityEngine;

namespace UniMasterLinker.Editor
{
    /// <summary>
    ///     ゲームマスターのAPIクラスを更新するエディタ拡張
    /// </summary>
    public class UpdateGameMasterAPIClass : EditorWindow
    {
        private const string DataRootPath = "/UniMasterLinker/Scripts/API/";

        /// <summary>
        ///     APIクラスの更新
        /// </summary>
        [MenuItem("UniMasterLinker/APIクラスの更新")]
        private static async void UpdateAPIClassFile()
        {
            // 実装例
            // var playerGameInfo = GoogleSheetUtil.GetGameInfo(Constant.Constant.GameMasterSheetURL,
            //     Constant.Constant.PlayerSheetName);
            //
            // var (playerPramJson) =
            //     await UniTask.WhenAll(playerGameInfo);
            //
            // // プレイヤーの初期パラメータAPIクラスを生成
            // CreateParamAPIClassFile(playerPramJson, Constant.Constant.PlayerSheetName);
        }

        /// <summary>
        /// パラメータのAPIクラスの作成
        /// </summary>
        /// <param name="paramJson"></param>
        /// <param name="fileName"></param>
        private static void CreateParamAPIClassFile(string paramJson, string fileName)
        {
            var paramString = CreateParameterContents(paramJson);
            var scriptContent = CreateScriptContent(fileName, paramString);
            CreateScript(fileName, scriptContent);
        }

        /// <summary>
        ///     スクリプトファイルを生成
        /// </summary>
        /// <param name="path"></param>
        /// <param name="content"></param>
        private static void CreateScript(string path, string content)
        {
            path = Application.dataPath + "/" + DataRootPath +"/" + path + ".cs";

            using (var writer = new StreamWriter(path, false))
            {
                writer.WriteLine(content);
            }

            AssetDatabase.Refresh();
        }

        /// <summary>
        ///     スクリプトの内容を生成
        /// </summary>
        /// <param name="className"></param>
        /// <param name="parameterContents"></param>
        /// <returns></returns>
        private static string CreateScriptContent(string className, string parameterContents)
        {
            return $@"// <auto-generated/>
// このコードは自動生成されたものです。手動で編集しないでください。
using System.Collections.Generic;
using UnityEngine;

namespace API
{{
    /// <summary>
    /// マスターデータから取得する際の{className}パラメータクラス
    /// </summary>
    [System.Serializable]
    public partial class {className}Data
    {{
        {parameterContents}
    }}

    /// <summary>
    /// マスターデータから取得する際にレスポンスクラス
    /// </summary>
    [System.Serializable]
    public class {className}Response : ResponseBase<{className}Data>
    {{
    }}
}}";
        }

        /// <summary>
        ///     パラメータの内容を生成
        /// </summary>
        /// <returns></returns>
        private static string CreateParameterContents(string paramJson)
        {
            var parameterKeyList = GoogleSheetUtil.GetParameterKeyList(paramJson);
            var parameterTypeList = GoogleSheetUtil.GetParameterTypeList(paramJson);
            var parameterDescriptionList = GoogleSheetUtil.GetParameterDescriptionList(paramJson);
            return CreateParameterClassContents(parameterKeyList, parameterTypeList, parameterDescriptionList);
        }

        /// <summary>
        ///     パラメータの内容を生成
        /// </summary>
        /// <param name="keys"></param>
        /// <param name="types"></param>
        /// <param name="descriptions"></param>
        /// <returns></returns>
        private static string CreateParameterClassContents(IReadOnlyList<string> keys, IReadOnlyList<string> types,
            IReadOnlyList<string> descriptions)
        {
            var parameterString = new StringBuilder();
            
            for (var keyIndex = 0; keyIndex < keys.Count; keyIndex++)
            {
                var key = keys[keyIndex];
                // Summary文の作成
                var descriptionValue = string.IsNullOrEmpty(descriptions[keyIndex]) ? key : descriptions[keyIndex];
                var summaryString = $"/// <summary>\n        /// {descriptionValue}\n        /// </summary>\n";
                if (keyIndex == 0)
                {
                    parameterString.Append(
                        $"{summaryString}        public {types[keyIndex]} " +
                        key +
                        ";\n\n");
                }
                else if (keyIndex == keys.Count - 1)
                {
                    parameterString.Append(
                        $"\t\t{summaryString}        public {types[keyIndex]} " +
                                           key + ";");
                }
                else
                {
                    parameterString.Append(
                        $"\t\t{summaryString}        public {types[keyIndex]} " +
                        key + ";\n\n");
                }
            }

            return parameterString.ToString();
        }
    }
}
#endif